# Travis-CI Build for SimpleAmqpClient
# see travis-ci.org for details

language: cpp

sudo: required

compiler:
    - gcc
    - clang

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev

install:
    - git clone https://github.com/matt-42/iod.git
    - mkdir -p iod/build
    - cd iod/build
    - cmake ..
